---
name: WebService-KuronekoYamato
version: 0.0.1
author:
  - 'OONO Yoshitaka <aab61120@pop12.odn.ne.jp>'
abstract: 'Check Track Shipments (Yamato Transport Co., Ltd. /Japan)'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Encode: 0
  Test::More: 0
  WWW::Mechanize: 0
  Web::Scrape: 0
  YAML::Syck: 0
  version: 0
provides:
  WebService::KuronekoYamato:
    file: lib/WebService/KuronekoYamato.pm
    version: !!perl/hash:version
      original: 0.0.1
      qv: 1
      version:
        - 0
        - 0
        - 1
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
