# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-KuronekoYamato
version:      0.0.2
version_from: lib/WebService/KuronekoYamato.pm
installdirs:  site
requires:
    Encode:                        0
    Test::More:                    0
    version:                       0
    Web::Scraper:                  0
    WWW::Mechanize:                0
    YAML::Syck:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
